#!/bin/sh
echo "Beginning AVR128DA/AVR128DB with default serial pins (36 files)..."
make OS=linux ENV=arduino 128dx_ser0_extr
make OS=linux ENV=arduino 128dx_ser1_extr
make OS=linux ENV=arduino 128dx_ser2_extr
make OS=linux ENV=arduino 128dx_ser3_extr
make OS=linux ENV=arduino 128dx_ser4_extr
make OS=linux ENV=arduino 128dx_ser5_extr
make OS=linux ENV=arduino 128dx_ser0_all_8sec
make OS=linux ENV=arduino 128dx_ser1_all_8sec
make OS=linux ENV=arduino 128dx_ser2_all_8sec
make OS=linux ENV=arduino 128dx_ser3_all_8sec
make OS=linux ENV=arduino 128dx_ser4_all_8sec
make OS=linux ENV=arduino 128dx_ser5_all_8sec
make OS=linux ENV=arduino 128dx_ser0_poronly_8sec
make OS=linux ENV=arduino 128dx_ser1_poronly_8sec
make OS=linux ENV=arduino 128dx_ser2_poronly_8sec
make OS=linux ENV=arduino 128dx_ser3_poronly_8sec
make OS=linux ENV=arduino 128dx_ser4_poronly_8sec
make OS=linux ENV=arduino 128dx_ser5_poronly_8sec
make OS=linux ENV=arduino 128dx_ser0_extronly
make OS=linux ENV=arduino 128dx_ser1_extronly
make OS=linux ENV=arduino 128dx_ser2_extronly
make OS=linux ENV=arduino 128dx_ser3_extronly
make OS=linux ENV=arduino 128dx_ser4_extronly
make OS=linux ENV=arduino 128dx_ser5_extronly
make OS=linux ENV=arduino 128dx_ser0_swronly_8sec
make OS=linux ENV=arduino 128dx_ser1_swronly_8sec
make OS=linux ENV=arduino 128dx_ser2_swronly_8sec
make OS=linux ENV=arduino 128dx_ser3_swronly_8sec
make OS=linux ENV=arduino 128dx_ser4_swronly_8sec
make OS=linux ENV=arduino 128dx_ser5_swronly_8sec
make OS=linux ENV=arduino 128dx_ser0_extr_8sec
make OS=linux ENV=arduino 128dx_ser1_extr_8sec
make OS=linux ENV=arduino 128dx_ser2_extr_8sec
make OS=linux ENV=arduino 128dx_ser3_extr_8sec
make OS=linux ENV=arduino 128dx_ser4_extr_8sec
make OS=linux ENV=arduino 128dx_ser5_extr_8sec
echo "Beginning AVR128DA/AVR128DB with alternate serial pins (36 files)..."
make OS=linux ENV=arduino 128dx_ser0_alt_extr
make OS=linux ENV=arduino 128dx_ser1_alt_extr
make OS=linux ENV=arduino 128dx_ser2_alt_extr
make OS=linux ENV=arduino 128dx_ser3_alt_extr
make OS=linux ENV=arduino 128dx_ser4_alt_extr
make OS=linux ENV=arduino 128dx_ser5_alt_extr
make OS=linux ENV=arduino 128dx_ser0_alt_all_8sec
make OS=linux ENV=arduino 128dx_ser1_alt_all_8sec
make OS=linux ENV=arduino 128dx_ser2_alt_all_8sec
make OS=linux ENV=arduino 128dx_ser3_alt_all_8sec
make OS=linux ENV=arduino 128dx_ser4_alt_all_8sec
make OS=linux ENV=arduino 128dx_ser5_alt_all_8sec
make OS=linux ENV=arduino 128dx_ser0_alt_poronly_8sec
make OS=linux ENV=arduino 128dx_ser1_alt_poronly_8sec
make OS=linux ENV=arduino 128dx_ser2_alt_poronly_8sec
make OS=linux ENV=arduino 128dx_ser3_alt_poronly_8sec
make OS=linux ENV=arduino 128dx_ser4_alt_poronly_8sec
make OS=linux ENV=arduino 128dx_ser5_alt_poronly_8sec
make OS=linux ENV=arduino 128dx_ser0_alt_extronly
make OS=linux ENV=arduino 128dx_ser1_alt_extronly
make OS=linux ENV=arduino 128dx_ser2_alt_extronly
make OS=linux ENV=arduino 128dx_ser3_alt_extronly
make OS=linux ENV=arduino 128dx_ser4_alt_extronly
make OS=linux ENV=arduino 128dx_ser5_alt_extronly
make OS=linux ENV=arduino 128dx_ser0_alt_swronly_8sec
make OS=linux ENV=arduino 128dx_ser1_alt_swronly_8sec
make OS=linux ENV=arduino 128dx_ser2_alt_swronly_8sec
make OS=linux ENV=arduino 128dx_ser3_alt_swronly_8sec
make OS=linux ENV=arduino 128dx_ser4_alt_swronly_8sec
make OS=linux ENV=arduino 128dx_ser5_alt_swronly_8sec
make OS=linux ENV=arduino 128dx_ser0_alt_extr_8sec
make OS=linux ENV=arduino 128dx_ser1_alt_extr_8sec
make OS=linux ENV=arduino 128dx_ser2_alt_extr_8sec
make OS=linux ENV=arduino 128dx_ser3_alt_extr_8sec
make OS=linux ENV=arduino 128dx_ser4_alt_extr_8sec
make OS=linux ENV=arduino 128dx_ser5_alt_extr_8sec
echo "Beginning AVR64DA/AVR64DB with default serial pins (36 files)..."
make OS=linux ENV=arduino 64dx_ser0_extr
make OS=linux ENV=arduino 64dx_ser1_extr
make OS=linux ENV=arduino 64dx_ser2_extr
make OS=linux ENV=arduino 64dx_ser3_extr
make OS=linux ENV=arduino 64dx_ser4_extr
make OS=linux ENV=arduino 64dx_ser5_extr
make OS=linux ENV=arduino 64dx_ser0_all_8sec
make OS=linux ENV=arduino 64dx_ser1_all_8sec
make OS=linux ENV=arduino 64dx_ser2_all_8sec
make OS=linux ENV=arduino 64dx_ser3_all_8sec
make OS=linux ENV=arduino 64dx_ser4_all_8sec
make OS=linux ENV=arduino 64dx_ser5_all_8sec
make OS=linux ENV=arduino 64dx_ser0_poronly_8sec
make OS=linux ENV=arduino 64dx_ser1_poronly_8sec
make OS=linux ENV=arduino 64dx_ser2_poronly_8sec
make OS=linux ENV=arduino 64dx_ser3_poronly_8sec
make OS=linux ENV=arduino 64dx_ser4_poronly_8sec
make OS=linux ENV=arduino 64dx_ser5_poronly_8sec
make OS=linux ENV=arduino 64dx_ser0_extronly
make OS=linux ENV=arduino 64dx_ser1_extronly
make OS=linux ENV=arduino 64dx_ser2_extronly
make OS=linux ENV=arduino 64dx_ser3_extronly
make OS=linux ENV=arduino 64dx_ser4_extronly
make OS=linux ENV=arduino 64dx_ser5_extronly
make OS=linux ENV=arduino 64dx_ser0_swronly_8sec
make OS=linux ENV=arduino 64dx_ser1_swronly_8sec
make OS=linux ENV=arduino 64dx_ser2_swronly_8sec
make OS=linux ENV=arduino 64dx_ser3_swronly_8sec
make OS=linux ENV=arduino 64dx_ser4_swronly_8sec
make OS=linux ENV=arduino 64dx_ser5_swronly_8sec
make OS=linux ENV=arduino 64dx_ser0_extr_8sec
make OS=linux ENV=arduino 64dx_ser1_extr_8sec
make OS=linux ENV=arduino 64dx_ser2_extr_8sec
make OS=linux ENV=arduino 64dx_ser3_extr_8sec
make OS=linux ENV=arduino 64dx_ser4_extr_8sec
make OS=linux ENV=arduino 64dx_ser5_extr_8sec
echo "Beginning AVR64DA/AVR64DB with alternate serial pins (36 files)..."
make OS=linux ENV=arduino 64dx_ser0_alt_extr
make OS=linux ENV=arduino 64dx_ser1_alt_extr
make OS=linux ENV=arduino 64dx_ser2_alt_extr
make OS=linux ENV=arduino 64dx_ser3_alt_extr
make OS=linux ENV=arduino 64dx_ser4_alt_extr
make OS=linux ENV=arduino 64dx_ser5_alt_extr
make OS=linux ENV=arduino 64dx_ser0_alt_all_8sec
make OS=linux ENV=arduino 64dx_ser1_alt_all_8sec
make OS=linux ENV=arduino 64dx_ser2_alt_all_8sec
make OS=linux ENV=arduino 64dx_ser3_alt_all_8sec
make OS=linux ENV=arduino 64dx_ser4_alt_all_8sec
make OS=linux ENV=arduino 64dx_ser5_alt_all_8sec
make OS=linux ENV=arduino 64dx_ser0_alt_poronly_8sec
make OS=linux ENV=arduino 64dx_ser1_alt_poronly_8sec
make OS=linux ENV=arduino 64dx_ser2_alt_poronly_8sec
make OS=linux ENV=arduino 64dx_ser3_alt_poronly_8sec
make OS=linux ENV=arduino 64dx_ser4_alt_poronly_8sec
make OS=linux ENV=arduino 64dx_ser5_alt_poronly_8sec
make OS=linux ENV=arduino 64dx_ser0_alt_extronly
make OS=linux ENV=arduino 64dx_ser1_alt_extronly
make OS=linux ENV=arduino 64dx_ser2_alt_extronly
make OS=linux ENV=arduino 64dx_ser3_alt_extronly
make OS=linux ENV=arduino 64dx_ser4_alt_extronly
make OS=linux ENV=arduino 64dx_ser5_alt_extronly
make OS=linux ENV=arduino 64dx_ser0_alt_swronly_8sec
make OS=linux ENV=arduino 64dx_ser1_alt_swronly_8sec
make OS=linux ENV=arduino 64dx_ser2_alt_swronly_8sec
make OS=linux ENV=arduino 64dx_ser3_alt_swronly_8sec
make OS=linux ENV=arduino 64dx_ser4_alt_swronly_8sec
make OS=linux ENV=arduino 64dx_ser5_alt_swronly_8sec
make OS=linux ENV=arduino 64dx_ser0_alt_extr_8sec
make OS=linux ENV=arduino 64dx_ser1_alt_extr_8sec
make OS=linux ENV=arduino 64dx_ser2_alt_extr_8sec
make OS=linux ENV=arduino 64dx_ser3_alt_extr_8sec
make OS=linux ENV=arduino 64dx_ser4_alt_extr_8sec
make OS=linux ENV=arduino 64dx_ser5_alt_extr_8sec
echo "Beginning AVR32DA/AVR32DB with default serial pins (30 files)..."
make OS=linux ENV=arduino 32dx_ser0_extr
make OS=linux ENV=arduino 32dx_ser1_extr
make OS=linux ENV=arduino 32dx_ser2_extr
make OS=linux ENV=arduino 32dx_ser3_extr
make OS=linux ENV=arduino 32dx_ser4_extr
make OS=linux ENV=arduino 32dx_ser0_all_8sec
make OS=linux ENV=arduino 32dx_ser1_all_8sec
make OS=linux ENV=arduino 32dx_ser2_all_8sec
make OS=linux ENV=arduino 32dx_ser3_all_8sec
make OS=linux ENV=arduino 32dx_ser4_all_8sec
make OS=linux ENV=arduino 32dx_ser0_poronly_8sec
make OS=linux ENV=arduino 32dx_ser1_poronly_8sec
make OS=linux ENV=arduino 32dx_ser2_poronly_8sec
make OS=linux ENV=arduino 32dx_ser3_poronly_8sec
make OS=linux ENV=arduino 32dx_ser4_poronly_8sec
make OS=linux ENV=arduino 32dx_ser0_extronly
make OS=linux ENV=arduino 32dx_ser1_extronly
make OS=linux ENV=arduino 32dx_ser2_extronly
make OS=linux ENV=arduino 32dx_ser3_extronly
make OS=linux ENV=arduino 32dx_ser4_extronly
make OS=linux ENV=arduino 32dx_ser0_swronly_8sec
make OS=linux ENV=arduino 32dx_ser1_swronly_8sec
make OS=linux ENV=arduino 32dx_ser2_swronly_8sec
make OS=linux ENV=arduino 32dx_ser3_swronly_8sec
make OS=linux ENV=arduino 32dx_ser4_swronly_8sec
make OS=linux ENV=arduino 32dx_ser0_extr_8sec
make OS=linux ENV=arduino 32dx_ser1_extr_8sec
make OS=linux ENV=arduino 32dx_ser2_extr_8sec
make OS=linux ENV=arduino 32dx_ser3_extr_8sec
make OS=linux ENV=arduino 32dx_ser4_extr_8sec
echo "Beginning AVR32DA/AVR32DB with alternate serial pins (24 files)..."
make OS=linux ENV=arduino 32dx_ser0_alt_extr
make OS=linux ENV=arduino 32dx_ser1_alt_extr
make OS=linux ENV=arduino 32dx_ser2_alt_extr
make OS=linux ENV=arduino 32dx_ser3_alt_extr
make OS=linux ENV=arduino 32dx_ser0_alt_all_8sec
make OS=linux ENV=arduino 32dx_ser1_alt_all_8sec
make OS=linux ENV=arduino 32dx_ser2_alt_all_8sec
make OS=linux ENV=arduino 32dx_ser3_alt_all_8sec
make OS=linux ENV=arduino 32dx_ser0_alt_poronly_8sec
make OS=linux ENV=arduino 32dx_ser1_alt_poronly_8sec
make OS=linux ENV=arduino 32dx_ser2_alt_poronly_8sec
make OS=linux ENV=arduino 32dx_ser3_alt_poronly_8sec
make OS=linux ENV=arduino 32dx_ser0_alt_extronly
make OS=linux ENV=arduino 32dx_ser1_alt_extronly
make OS=linux ENV=arduino 32dx_ser2_alt_extronly
make OS=linux ENV=arduino 32dx_ser3_alt_extronly
make OS=linux ENV=arduino 32dx_ser0_alt_swronly_8sec
make OS=linux ENV=arduino 32dx_ser1_alt_swronly_8sec
make OS=linux ENV=arduino 32dx_ser2_alt_swronly_8sec
make OS=linux ENV=arduino 32dx_ser3_alt_swronly_8sec
make OS=linux ENV=arduino 32dx_ser0_alt_extr_8sec
make OS=linux ENV=arduino 32dx_ser1_alt_extr_8sec
make OS=linux ENV=arduino 32dx_ser2_alt_extr_8sec
make OS=linux ENV=arduino 32dx_ser3_alt_extr_8sec
echo "Done with AVR DA/DB-series."
echo "36 + 36 + 36 + 36 = 144 128 and 64k versions, and 30 + 24 = 54 for 32k"
echo "Hence there should b 144 +  54 = 198 hex files for AVR Dx."
