name=RTC_Sleep
version=1.0.0
author=WKE67
maintainer=WKE67 <wke67@t-online.de>
sentence=DxCore library providing very low power sleep - time controlled by RTC.
paragraph=
category=Low Power
url=
architectures=megaavr
