name: Check code formatting

on:
  pull_request:
    paths:
      - ".github/workflows/check-code-formatting.yml"
      - "megaavr/bootloaders/**"
#      - "megaavr/cores/**"
      - "megaavr/libraries/**"
      - "megaavr/variants/**"
  push:
    paths:
      - ".github/workflows/check-code-formatting.yml"
      - "megaavr/bootloaders/**"
#      - "megaavr/cores/**"
      - "megaavr/libraries/**"
      - "megaavr/variants/**"
  # workflow_dispatch event allows the workflow to be triggered manually
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # repository_dispatch event allows the workflow to be triggered via the GitHub API
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

env:
  OPTIONS_FILE_PATH: megaavr/extras/ci/arduino-code-style.conf
  NAME_PATTERNS: |
    - '*.ino'
    - '*.h'
    - '*.hpp'
    - '*.hh'
    - '*.hxx'
    - '*.h++'
    - '*.cpp'
    - '*.cc'
    - '*.cxx'
    - '*.c++'
    - '*.cp'
    - '*.c'
    - '*.ipp'
    - '*.ii'
    - '*.ixx'
    - '*.inl'
    - '*.tpp'
    - '*.txx'
    - '*.tpl'

jobs:
  bootloaders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check code formatting
        uses: spencekonde/artistic-style-action@main
        with:
          options-file-path: ${{ env.OPTIONS_FILE_PATH }}
          name-patterns: |
            ${{ env.NAME_PATTERNS }}
          target-paths: |
            - megaavr/bootloaders

#  cores:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4

#      - name: Check code formatting
#        uses: per1234/artistic-style-action@main
#        with:
#          options-file-path: ${{ env.OPTIONS_FILE_PATH }}
#          name-patterns: |
#            ${{ env.NAME_PATTERNS }}
#          target-paths: |
#            - megaavr/cores

  libraries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check code formatting
        uses: per1234/artistic-style-action@main
        with:
          options-file-path: ${{ env.OPTIONS_FILE_PATH }}
          name-patterns: |
            ${{ env.NAME_PATTERNS }}
          target-paths: |
            - megaavr/libraries

  variants:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check code formatting
        uses: per1234/artistic-style-action@main
        with:
          options-file-path: ${{ env.OPTIONS_FILE_PATH }}
          name-patterns: |
            ${{ env.NAME_PATTERNS }}
          target-paths: |
            - megaavr/variants
