name: Compile Examples Macros

on:
  # workflow_dispatch event allows the workflow to be triggered manually
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # repository_dispatch event allows the workflow to be triggered via the GitHub API
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  compile-examples:
    runs-on: ubuntu-latest

    env:
      platform-name: DxCore:megaavr

      all-parts-sketch-paths: |
        - megaavr/extras/ci/test-sketch/all/dummysketch
        - megaavr/extras/ci/test-sketch/all/macros
    strategy:
      fail-fast: false

      matrix:
        flash-class:
          - 128
          - 64
          - 32
          - 16
        device-family:
          - da
          - db
          - dd
          - du
          - ea
          - eb
          - ec
          - la
        pincount:
          - 64
          - 48
          - 32
          - 28
          - 20
          - 14
        clocksource:
          - internal
          - extclock
          - crystal
        int-osc:
          - 20
          - 24
        mvio:
          - mvio=disabled,
          - mvioopti=disabled,
            - ""
        opti:
          - opti
          - ""

        # Filter out these matrix combinations

        exclude:
          # for quick test
          - device-family: da
          - device-family: db
          - device-family: du
          - device-family: ea
          - device-family: eb
          - clocksource: extclock
          - clocksource: crystal

          # for DD only
          - int-osc: 20
          - device-family: dd
            mvio: mvioopti=disabled,
            opti: ""
          - device-family: dd
            mvio: mvio=disabled,
            opti: "opti"
          - device-family: da
            mvio: mvio=disabled,
          - device-family: db
            mvio: mvio=disabled,
          - device-family: du
            mvio: mvio=disabled,
          - device-family: ea
            mvio: mvio=disabled,
          - device-family: eb
            mvio: mvio=disabled,
          - device-family: da
            mvio: mvioopti=disabled,
          - device-family: db
            mvio: mvioopti=disabled,
          - device-family: du
            mvio: mvioopti=disabled,
          - device-family: ea
            mvio: mvioopti=disabled,
          - device-family: eb
            mvio: mvioopti=disabled,
          - device-family: da
            opti: opti
          - device-family: db
            opti: opti
          - device-family: du
            opti: opti
          - device-family: ea
            opti: opti
          - device-family: eb
            opti: opti

          # Filter avaliable parts for DA DB DU
          # Things w/out xtals
          - device-family: da
            clocksource: crystal

          # DA limits. No 8/16k flash, no 32k 64-pin. No 20/14 pin.
          - device-family: da
            flash-class: 32
            pincount: 64
          - device-family: da
            flash-class: 16
          - device-family: da
            pincount: 20
          - device-family: da
            pincount: 14

          # DB limits. No 8/16k flash, no 32k 64-pin. No 20/14 pin.
          - device-family: db
            flash-class: 32
            pincount: 64
          - device-family: db
            flash-class: 16
          - device-family: db
            pincount: 20
          - device-family: db
            pincount: 14

          # DD limits. No 128k/8k flash, no 64/48 pin.
          - device-family: dd
            flash-class: 128
          - device-family: dd
            pincount: 64
          - device-family: dd
            pincount: 48

          # DU limits. No 128k/8k flash, no 64/48 pin. No 64k 20/14pin.
          - device-family: du
            flash-class: 128
          - device-family: du
            pincount: 64
          - device-family: du
            pincount: 48
          - device-family: du
            pincount: 20
            flash-class: 64
          - device-family: du
            pincount: 14
            flash-class: 64

          # Filter avaliable parts for EA EB EC LA
          # Things we can't get yet
          - device-family: ec
          - device-family: la
          # Things w/out xtals
          - device-family: eb
            clocksource: crystal
          # Internal Clock
          - device-family: ea
            int-osc: 24
          - device-family: eb
            int-osc: 24

          # Pincounts
          - device-family: eb
            pincount: 64
          - device-family: eb
            pincount: 48
          - device-family: ea
            pincount: 64
          - device-family: la
            pincount: 64
          - device-family: la
            pincount: 48
          - device-family: ea
            pincount: 14
          - device-family: ea
            pincount: 20

          #flashsizes
          - device-family: ea
            flash-class: 128
          - device-family: eb
            flash-class: 64
          - device-family: eb
            flash-class: 128
          - device-family: la
            flash-class: 64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: macrosII

      # See: https://github.com/arduino/compile-sketches/README.md

      - name: Compile examples (rated max speed, nothing weird)
        uses: arduino/compile-sketches@main
        with:
          cli-version: 0.33.0
          fqbn: ${{ env.platform-name }}:avr${{ matrix.device-family }}${{ matrix.opti }}:chip=avr${{ matrix.flash-class }}${{ matrix.device-family }}${{ matrix.pincount }},clock=${{matrix.int-osc}}${{ matrix.clocksource }},${{ matrix.mvio }}wiremode=mands,flmap=lockdefault
          sketch-paths: |
            # It's necessary to jump through some hoops to dynamically generate the env object keys to define the non-universal sketch paths
            # https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#format
            ${{ env.all-parts-sketch-paths }}
          platforms: |
            # Install DxCore via Boards Manager for the toolchain
            - source-url: http://drazzy.com/package_drazzy.com_index.json
              name: ${{ env.platform-name }}
            # Overwrite the DxCore release version with the platform from the local path
            - source-path: megaavr
              name: ${{ env.platform-name }}
          libraries: |
            # The sketches don't have any external library dependencies, so just define an empty array
            -
          verbose: false
          enable-deltas-report: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-warnings-report: true
          sketches-report-path: sketches-reports
